# Generated by Django 3.2.5 on 2021-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
